runner:
  type: crane
  platform: linux/amd64
  workers: 3


images:
  - "nginx:latest"
  - "ghcr.io/sagernet/sing-box:latest"
  - "ghcr.io/sagernet/sing-box:latest-testing"

rules:
  - match: all
    target: registry.local.y3-3am.top/aliyun
    mode: basename

# 全局配置      
log-level: info

docker-library:
  local:
    registry.local.y3-3am.top:
      - usename:
      - password:
  aliyun:
    
